name: test workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

job:
   hello-job:
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v2
         
  
     
      
