name: test workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  GLOBAL_VAR: 'I am global'

jobs:
   hello-job:
      runs-on: ubuntu-latest
      env: 
        JOb_SPECIFIC: 'I am job specific'
      steps:
         - name: step with env var
           env: 
             STEP_VAR: 'I am step specific'
           run: echo "step variable- $STEP_VAR"  
         - uses: actions/checkout@v2
         - name: print global variable
           run: echo "Global variable- $GLOBAL_VAR"
         - name: print job variable
           run: echo "JOB variable- $JOb_SPECIFIC"
         - name: user secret variable
           run: echo "Secret is - $DB_PASSWORD"  
           env:
             DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
     

         
  
     
      
