name: test workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  GLOBAL_VAR: 'I am global'

jobs:
   hello-job:
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v2
         - name: print global variable
           run: echo "Global: $GLOBAL_VAR"

         
  
     
      
